/********************************************************************************
** Form generated from reading UI file 'connect4app.ui'
**
** Created by: Qt User Interface Compiler version 5.12.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CONNECT4APP_H
#define UI_CONNECT4APP_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_connect4App
{
public:
    QAction *actionClose_Application;
    QAction *actionClose_Application_2;
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *firstPlayerSelection;
    QFrame *playerInfoFrame1;
    QLineEdit *enteredName;
    QLabel *nameLabel;
    QPushButton *redButton;
    QLabel *colorLabel;
    QPushButton *greenButton;
    QPushButton *cyanButton;
    QPushButton *blueButton;
    QPushButton *yellowButton;
    QPushButton *magentaButton;
    QPushButton *maroonButton;
    QPushButton *goldButton;
    QPushButton *darkMagButton;
    QPushButton *darkGreenButton;
    QPushButton *blackButton;
    QPushButton *whiteButton;
    QPushButton *nextButton;
    QLabel *currentColLabel_2;
    QLabel *currentCol_2;
    QWidget *secondPlayerSelection;
    QFrame *playerInfoFrame2;
    QLineEdit *enteredName_2;
    QLabel *nameLabel_2;
    QPushButton *redButton_2;
    QLabel *colorLabel_2;
    QPushButton *greenButton_2;
    QPushButton *cyanButton_2;
    QPushButton *blueButton_2;
    QPushButton *yellowButton_2;
    QPushButton *magentaButton_2;
    QPushButton *maroonButton_2;
    QPushButton *goldButton_2;
    QPushButton *darkMagButton_2;
    QPushButton *darkGreenButton_2;
    QPushButton *blackButton_2;
    QPushButton *whiteButton_2;
    QPushButton *nextButton_2;
    QLabel *currentColLabel;
    QLabel *currentCol;
    QWidget *playerGoFirst;
    QFrame *frame;
    QPushButton *nextButton_3;
    QLabel *label;
    QPushButton *name1Button;
    QPushButton *name2Button;
    QWidget *gameSection;
    QFrame *gameFrame;
    QLabel *space_1_1;
    QLabel *space_1_2;
    QLabel *space_1_3;
    QLabel *space_1_5;
    QLabel *space_1_4;
    QLabel *space_1_6;
    QLabel *space_2_5;
    QLabel *space_2_3;
    QLabel *space_2_4;
    QLabel *space_2_6;
    QLabel *space_2_2;
    QLabel *space_2_1;
    QLabel *space_3_5;
    QLabel *space_3_3;
    QLabel *space_3_4;
    QLabel *space_3_6;
    QLabel *space_3_2;
    QLabel *space_3_1;
    QLabel *space_4_5;
    QLabel *space_4_3;
    QLabel *space_4_4;
    QLabel *space_4_6;
    QLabel *space_4_2;
    QLabel *space_4_1;
    QLabel *space_5_5;
    QLabel *space_5_3;
    QLabel *space_5_4;
    QLabel *space_5_6;
    QLabel *space_5_2;
    QLabel *space_5_1;
    QLabel *space_6_5;
    QLabel *space_6_3;
    QLabel *space_6_4;
    QLabel *space_6_6;
    QLabel *space_6_2;
    QLabel *space_6_1;
    QLabel *space_7_5;
    QLabel *space_7_3;
    QLabel *space_7_4;
    QLabel *space_7_6;
    QLabel *space_7_2;
    QLabel *space_7_1;
    QPushButton *secondColButton;
    QPushButton *firstColButton;
    QPushButton *sixthButtonCol;
    QPushButton *fourthColButton;
    QPushButton *fifthColButton;
    QPushButton *thirdColButton;
    QLabel *player_label;
    QPushButton *instructionsButton;
    QPushButton *seventhColButton;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QMenuBar *menubar;
    QMenu *menuFile;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *connect4App)
    {
        if (connect4App->objectName().isEmpty())
            connect4App->setObjectName(QString::fromUtf8("connect4App"));
        connect4App->resize(1004, 722);
        actionClose_Application = new QAction(connect4App);
        actionClose_Application->setObjectName(QString::fromUtf8("actionClose_Application"));
        actionClose_Application_2 = new QAction(connect4App);
        actionClose_Application_2->setObjectName(QString::fromUtf8("actionClose_Application_2"));
        centralwidget = new QWidget(connect4App);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(-10, 10, 1001, 671));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        stackedWidget->setFont(font);
        firstPlayerSelection = new QWidget();
        firstPlayerSelection->setObjectName(QString::fromUtf8("firstPlayerSelection"));
        playerInfoFrame1 = new QFrame(firstPlayerSelection);
        playerInfoFrame1->setObjectName(QString::fromUtf8("playerInfoFrame1"));
        playerInfoFrame1->setGeometry(QRect(120, 60, 771, 561));
        playerInfoFrame1->setFrameShape(QFrame::StyledPanel);
        playerInfoFrame1->setFrameShadow(QFrame::Raised);
        enteredName = new QLineEdit(playerInfoFrame1);
        enteredName->setObjectName(QString::fromUtf8("enteredName"));
        enteredName->setGeometry(QRect(100, 40, 401, 51));
        QFont font1;
        font1.setPointSize(20);
        font1.setBold(true);
        font1.setItalic(true);
        font1.setWeight(75);
        enteredName->setFont(font1);
        enteredName->setAlignment(Qt::AlignCenter);
        nameLabel = new QLabel(playerInfoFrame1);
        nameLabel->setObjectName(QString::fromUtf8("nameLabel"));
        nameLabel->setGeometry(QRect(100, 10, 401, 20));
        nameLabel->setAlignment(Qt::AlignCenter);
        redButton = new QPushButton(playerInfoFrame1);
        redButton->setObjectName(QString::fromUtf8("redButton"));
        redButton->setGeometry(QRect(90, 130, 211, 71));
        QFont font2;
        font2.setPointSize(24);
        font2.setBold(true);
        font2.setWeight(75);
        redButton->setFont(font2);
        colorLabel = new QLabel(playerInfoFrame1);
        colorLabel->setObjectName(QString::fromUtf8("colorLabel"));
        colorLabel->setGeometry(QRect(100, 100, 401, 20));
        colorLabel->setAlignment(Qt::AlignCenter);
        greenButton = new QPushButton(playerInfoFrame1);
        greenButton->setObjectName(QString::fromUtf8("greenButton"));
        greenButton->setGeometry(QRect(90, 200, 211, 71));
        greenButton->setFont(font2);
        cyanButton = new QPushButton(playerInfoFrame1);
        cyanButton->setObjectName(QString::fromUtf8("cyanButton"));
        cyanButton->setGeometry(QRect(90, 270, 211, 71));
        cyanButton->setFont(font2);
        blueButton = new QPushButton(playerInfoFrame1);
        blueButton->setObjectName(QString::fromUtf8("blueButton"));
        blueButton->setGeometry(QRect(90, 340, 211, 71));
        blueButton->setFont(font2);
        yellowButton = new QPushButton(playerInfoFrame1);
        yellowButton->setObjectName(QString::fromUtf8("yellowButton"));
        yellowButton->setGeometry(QRect(90, 480, 211, 71));
        yellowButton->setFont(font2);
        magentaButton = new QPushButton(playerInfoFrame1);
        magentaButton->setObjectName(QString::fromUtf8("magentaButton"));
        magentaButton->setGeometry(QRect(90, 410, 211, 71));
        magentaButton->setFont(font2);
        maroonButton = new QPushButton(playerInfoFrame1);
        maroonButton->setObjectName(QString::fromUtf8("maroonButton"));
        maroonButton->setGeometry(QRect(300, 340, 211, 71));
        maroonButton->setFont(font2);
        goldButton = new QPushButton(playerInfoFrame1);
        goldButton->setObjectName(QString::fromUtf8("goldButton"));
        goldButton->setGeometry(QRect(300, 270, 211, 71));
        goldButton->setFont(font2);
        darkMagButton = new QPushButton(playerInfoFrame1);
        darkMagButton->setObjectName(QString::fromUtf8("darkMagButton"));
        darkMagButton->setGeometry(QRect(300, 480, 211, 71));
        darkMagButton->setFont(font2);
        darkGreenButton = new QPushButton(playerInfoFrame1);
        darkGreenButton->setObjectName(QString::fromUtf8("darkGreenButton"));
        darkGreenButton->setGeometry(QRect(300, 410, 211, 71));
        darkGreenButton->setFont(font2);
        blackButton = new QPushButton(playerInfoFrame1);
        blackButton->setObjectName(QString::fromUtf8("blackButton"));
        blackButton->setGeometry(QRect(300, 200, 211, 71));
        blackButton->setFont(font2);
        whiteButton = new QPushButton(playerInfoFrame1);
        whiteButton->setObjectName(QString::fromUtf8("whiteButton"));
        whiteButton->setGeometry(QRect(300, 130, 211, 71));
        whiteButton->setFont(font2);
        nextButton = new QPushButton(playerInfoFrame1);
        nextButton->setObjectName(QString::fromUtf8("nextButton"));
        nextButton->setGeometry(QRect(600, 480, 141, 71));
        QFont font3;
        font3.setPointSize(28);
        font3.setBold(true);
        font3.setWeight(75);
        nextButton->setFont(font3);
        currentColLabel_2 = new QLabel(playerInfoFrame1);
        currentColLabel_2->setObjectName(QString::fromUtf8("currentColLabel_2"));
        currentColLabel_2->setGeometry(QRect(540, 200, 221, 20));
        currentColLabel_2->setFont(font);
        currentColLabel_2->setAlignment(Qt::AlignCenter);
        currentCol_2 = new QLabel(playerInfoFrame1);
        currentCol_2->setObjectName(QString::fromUtf8("currentCol_2"));
        currentCol_2->setGeometry(QRect(560, 230, 191, 61));
        currentCol_2->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(firstPlayerSelection);
        secondPlayerSelection = new QWidget();
        secondPlayerSelection->setObjectName(QString::fromUtf8("secondPlayerSelection"));
        playerInfoFrame2 = new QFrame(secondPlayerSelection);
        playerInfoFrame2->setObjectName(QString::fromUtf8("playerInfoFrame2"));
        playerInfoFrame2->setGeometry(QRect(120, 60, 771, 561));
        playerInfoFrame2->setFrameShape(QFrame::StyledPanel);
        playerInfoFrame2->setFrameShadow(QFrame::Raised);
        enteredName_2 = new QLineEdit(playerInfoFrame2);
        enteredName_2->setObjectName(QString::fromUtf8("enteredName_2"));
        enteredName_2->setGeometry(QRect(100, 40, 401, 51));
        enteredName_2->setFont(font1);
        enteredName_2->setAlignment(Qt::AlignCenter);
        nameLabel_2 = new QLabel(playerInfoFrame2);
        nameLabel_2->setObjectName(QString::fromUtf8("nameLabel_2"));
        nameLabel_2->setGeometry(QRect(100, 10, 401, 20));
        nameLabel_2->setAlignment(Qt::AlignCenter);
        redButton_2 = new QPushButton(playerInfoFrame2);
        redButton_2->setObjectName(QString::fromUtf8("redButton_2"));
        redButton_2->setGeometry(QRect(90, 130, 211, 71));
        redButton_2->setFont(font2);
        colorLabel_2 = new QLabel(playerInfoFrame2);
        colorLabel_2->setObjectName(QString::fromUtf8("colorLabel_2"));
        colorLabel_2->setGeometry(QRect(100, 100, 401, 20));
        colorLabel_2->setAlignment(Qt::AlignCenter);
        greenButton_2 = new QPushButton(playerInfoFrame2);
        greenButton_2->setObjectName(QString::fromUtf8("greenButton_2"));
        greenButton_2->setGeometry(QRect(90, 200, 211, 71));
        greenButton_2->setFont(font2);
        cyanButton_2 = new QPushButton(playerInfoFrame2);
        cyanButton_2->setObjectName(QString::fromUtf8("cyanButton_2"));
        cyanButton_2->setGeometry(QRect(90, 270, 211, 71));
        cyanButton_2->setFont(font2);
        blueButton_2 = new QPushButton(playerInfoFrame2);
        blueButton_2->setObjectName(QString::fromUtf8("blueButton_2"));
        blueButton_2->setGeometry(QRect(90, 340, 211, 71));
        blueButton_2->setFont(font2);
        yellowButton_2 = new QPushButton(playerInfoFrame2);
        yellowButton_2->setObjectName(QString::fromUtf8("yellowButton_2"));
        yellowButton_2->setGeometry(QRect(90, 480, 211, 71));
        yellowButton_2->setFont(font2);
        magentaButton_2 = new QPushButton(playerInfoFrame2);
        magentaButton_2->setObjectName(QString::fromUtf8("magentaButton_2"));
        magentaButton_2->setGeometry(QRect(90, 410, 211, 71));
        magentaButton_2->setFont(font2);
        maroonButton_2 = new QPushButton(playerInfoFrame2);
        maroonButton_2->setObjectName(QString::fromUtf8("maroonButton_2"));
        maroonButton_2->setGeometry(QRect(300, 340, 211, 71));
        maroonButton_2->setFont(font2);
        goldButton_2 = new QPushButton(playerInfoFrame2);
        goldButton_2->setObjectName(QString::fromUtf8("goldButton_2"));
        goldButton_2->setGeometry(QRect(300, 270, 211, 71));
        goldButton_2->setFont(font2);
        darkMagButton_2 = new QPushButton(playerInfoFrame2);
        darkMagButton_2->setObjectName(QString::fromUtf8("darkMagButton_2"));
        darkMagButton_2->setGeometry(QRect(300, 480, 211, 71));
        darkMagButton_2->setFont(font2);
        darkGreenButton_2 = new QPushButton(playerInfoFrame2);
        darkGreenButton_2->setObjectName(QString::fromUtf8("darkGreenButton_2"));
        darkGreenButton_2->setGeometry(QRect(300, 410, 211, 71));
        darkGreenButton_2->setFont(font2);
        blackButton_2 = new QPushButton(playerInfoFrame2);
        blackButton_2->setObjectName(QString::fromUtf8("blackButton_2"));
        blackButton_2->setGeometry(QRect(300, 200, 211, 71));
        blackButton_2->setFont(font2);
        whiteButton_2 = new QPushButton(playerInfoFrame2);
        whiteButton_2->setObjectName(QString::fromUtf8("whiteButton_2"));
        whiteButton_2->setGeometry(QRect(300, 130, 211, 71));
        whiteButton_2->setFont(font2);
        nextButton_2 = new QPushButton(playerInfoFrame2);
        nextButton_2->setObjectName(QString::fromUtf8("nextButton_2"));
        nextButton_2->setGeometry(QRect(600, 480, 141, 71));
        nextButton_2->setFont(font3);
        currentColLabel = new QLabel(playerInfoFrame2);
        currentColLabel->setObjectName(QString::fromUtf8("currentColLabel"));
        currentColLabel->setGeometry(QRect(540, 200, 221, 20));
        currentColLabel->setFont(font);
        currentColLabel->setAlignment(Qt::AlignCenter);
        currentCol = new QLabel(playerInfoFrame2);
        currentCol->setObjectName(QString::fromUtf8("currentCol"));
        currentCol->setGeometry(QRect(560, 230, 191, 61));
        currentCol->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(secondPlayerSelection);
        playerGoFirst = new QWidget();
        playerGoFirst->setObjectName(QString::fromUtf8("playerGoFirst"));
        frame = new QFrame(playerGoFirst);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(120, 60, 771, 561));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        nextButton_3 = new QPushButton(frame);
        nextButton_3->setObjectName(QString::fromUtf8("nextButton_3"));
        nextButton_3->setGeometry(QRect(600, 480, 141, 71));
        nextButton_3->setFont(font3);
        label = new QLabel(frame);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(70, 40, 621, 91));
        QFont font4;
        font4.setPointSize(48);
        font4.setBold(true);
        font4.setWeight(75);
        label->setFont(font4);
        label->setAlignment(Qt::AlignCenter);
        name1Button = new QPushButton(frame);
        name1Button->setObjectName(QString::fromUtf8("name1Button"));
        name1Button->setGeometry(QRect(72, 180, 611, 91));
        name1Button->setFont(font4);
        name2Button = new QPushButton(frame);
        name2Button->setObjectName(QString::fromUtf8("name2Button"));
        name2Button->setGeometry(QRect(70, 280, 611, 91));
        name2Button->setFont(font4);
        stackedWidget->addWidget(playerGoFirst);
        gameSection = new QWidget();
        gameSection->setObjectName(QString::fromUtf8("gameSection"));
        gameFrame = new QFrame(gameSection);
        gameFrame->setObjectName(QString::fromUtf8("gameFrame"));
        gameFrame->setGeometry(QRect(130, 150, 711, 441));
        gameFrame->setFrameShape(QFrame::StyledPanel);
        gameFrame->setFrameShadow(QFrame::Raised);
        space_1_1 = new QLabel(gameFrame);
        space_1_1->setObjectName(QString::fromUtf8("space_1_1"));
        space_1_1->setGeometry(QRect(30, 30, 51, 31));
        space_1_1->setAlignment(Qt::AlignCenter);
        space_1_2 = new QLabel(gameFrame);
        space_1_2->setObjectName(QString::fromUtf8("space_1_2"));
        space_1_2->setGeometry(QRect(30, 100, 51, 31));
        space_1_2->setAlignment(Qt::AlignCenter);
        space_1_3 = new QLabel(gameFrame);
        space_1_3->setObjectName(QString::fromUtf8("space_1_3"));
        space_1_3->setGeometry(QRect(30, 170, 51, 31));
        space_1_3->setAlignment(Qt::AlignCenter);
        space_1_5 = new QLabel(gameFrame);
        space_1_5->setObjectName(QString::fromUtf8("space_1_5"));
        space_1_5->setGeometry(QRect(30, 310, 51, 31));
        space_1_5->setAlignment(Qt::AlignCenter);
        space_1_4 = new QLabel(gameFrame);
        space_1_4->setObjectName(QString::fromUtf8("space_1_4"));
        space_1_4->setGeometry(QRect(30, 240, 51, 31));
        space_1_4->setAlignment(Qt::AlignCenter);
        space_1_6 = new QLabel(gameFrame);
        space_1_6->setObjectName(QString::fromUtf8("space_1_6"));
        space_1_6->setGeometry(QRect(30, 380, 51, 31));
        space_1_6->setAlignment(Qt::AlignCenter);
        space_2_5 = new QLabel(gameFrame);
        space_2_5->setObjectName(QString::fromUtf8("space_2_5"));
        space_2_5->setGeometry(QRect(130, 310, 51, 31));
        space_2_5->setAlignment(Qt::AlignCenter);
        space_2_3 = new QLabel(gameFrame);
        space_2_3->setObjectName(QString::fromUtf8("space_2_3"));
        space_2_3->setGeometry(QRect(130, 170, 51, 31));
        space_2_3->setAlignment(Qt::AlignCenter);
        space_2_4 = new QLabel(gameFrame);
        space_2_4->setObjectName(QString::fromUtf8("space_2_4"));
        space_2_4->setGeometry(QRect(130, 240, 51, 31));
        space_2_4->setAlignment(Qt::AlignCenter);
        space_2_6 = new QLabel(gameFrame);
        space_2_6->setObjectName(QString::fromUtf8("space_2_6"));
        space_2_6->setGeometry(QRect(130, 380, 51, 31));
        space_2_6->setAlignment(Qt::AlignCenter);
        space_2_2 = new QLabel(gameFrame);
        space_2_2->setObjectName(QString::fromUtf8("space_2_2"));
        space_2_2->setGeometry(QRect(130, 100, 51, 31));
        space_2_2->setAlignment(Qt::AlignCenter);
        space_2_1 = new QLabel(gameFrame);
        space_2_1->setObjectName(QString::fromUtf8("space_2_1"));
        space_2_1->setGeometry(QRect(130, 30, 51, 31));
        space_2_1->setAlignment(Qt::AlignCenter);
        space_3_5 = new QLabel(gameFrame);
        space_3_5->setObjectName(QString::fromUtf8("space_3_5"));
        space_3_5->setGeometry(QRect(230, 310, 51, 31));
        space_3_5->setAlignment(Qt::AlignCenter);
        space_3_3 = new QLabel(gameFrame);
        space_3_3->setObjectName(QString::fromUtf8("space_3_3"));
        space_3_3->setGeometry(QRect(230, 170, 51, 31));
        space_3_3->setAlignment(Qt::AlignCenter);
        space_3_4 = new QLabel(gameFrame);
        space_3_4->setObjectName(QString::fromUtf8("space_3_4"));
        space_3_4->setGeometry(QRect(230, 240, 51, 31));
        space_3_4->setAlignment(Qt::AlignCenter);
        space_3_6 = new QLabel(gameFrame);
        space_3_6->setObjectName(QString::fromUtf8("space_3_6"));
        space_3_6->setGeometry(QRect(230, 380, 51, 31));
        space_3_6->setAlignment(Qt::AlignCenter);
        space_3_2 = new QLabel(gameFrame);
        space_3_2->setObjectName(QString::fromUtf8("space_3_2"));
        space_3_2->setGeometry(QRect(230, 100, 51, 31));
        space_3_2->setAlignment(Qt::AlignCenter);
        space_3_1 = new QLabel(gameFrame);
        space_3_1->setObjectName(QString::fromUtf8("space_3_1"));
        space_3_1->setGeometry(QRect(230, 30, 51, 31));
        space_3_1->setAlignment(Qt::AlignCenter);
        space_4_5 = new QLabel(gameFrame);
        space_4_5->setObjectName(QString::fromUtf8("space_4_5"));
        space_4_5->setGeometry(QRect(330, 310, 51, 31));
        space_4_5->setAlignment(Qt::AlignCenter);
        space_4_3 = new QLabel(gameFrame);
        space_4_3->setObjectName(QString::fromUtf8("space_4_3"));
        space_4_3->setGeometry(QRect(330, 170, 51, 31));
        space_4_3->setAlignment(Qt::AlignCenter);
        space_4_4 = new QLabel(gameFrame);
        space_4_4->setObjectName(QString::fromUtf8("space_4_4"));
        space_4_4->setGeometry(QRect(330, 240, 51, 31));
        space_4_4->setAlignment(Qt::AlignCenter);
        space_4_6 = new QLabel(gameFrame);
        space_4_6->setObjectName(QString::fromUtf8("space_4_6"));
        space_4_6->setGeometry(QRect(330, 380, 51, 31));
        space_4_6->setAlignment(Qt::AlignCenter);
        space_4_2 = new QLabel(gameFrame);
        space_4_2->setObjectName(QString::fromUtf8("space_4_2"));
        space_4_2->setGeometry(QRect(330, 100, 51, 31));
        space_4_2->setAlignment(Qt::AlignCenter);
        space_4_1 = new QLabel(gameFrame);
        space_4_1->setObjectName(QString::fromUtf8("space_4_1"));
        space_4_1->setGeometry(QRect(330, 30, 51, 31));
        space_4_1->setAlignment(Qt::AlignCenter);
        space_5_5 = new QLabel(gameFrame);
        space_5_5->setObjectName(QString::fromUtf8("space_5_5"));
        space_5_5->setGeometry(QRect(430, 310, 51, 31));
        space_5_5->setAlignment(Qt::AlignCenter);
        space_5_3 = new QLabel(gameFrame);
        space_5_3->setObjectName(QString::fromUtf8("space_5_3"));
        space_5_3->setGeometry(QRect(430, 170, 51, 31));
        space_5_3->setAlignment(Qt::AlignCenter);
        space_5_4 = new QLabel(gameFrame);
        space_5_4->setObjectName(QString::fromUtf8("space_5_4"));
        space_5_4->setGeometry(QRect(430, 240, 51, 31));
        space_5_4->setAlignment(Qt::AlignCenter);
        space_5_6 = new QLabel(gameFrame);
        space_5_6->setObjectName(QString::fromUtf8("space_5_6"));
        space_5_6->setGeometry(QRect(430, 380, 51, 31));
        space_5_6->setAlignment(Qt::AlignCenter);
        space_5_2 = new QLabel(gameFrame);
        space_5_2->setObjectName(QString::fromUtf8("space_5_2"));
        space_5_2->setGeometry(QRect(430, 100, 51, 31));
        space_5_2->setAlignment(Qt::AlignCenter);
        space_5_1 = new QLabel(gameFrame);
        space_5_1->setObjectName(QString::fromUtf8("space_5_1"));
        space_5_1->setGeometry(QRect(430, 30, 51, 31));
        space_5_1->setAlignment(Qt::AlignCenter);
        space_6_5 = new QLabel(gameFrame);
        space_6_5->setObjectName(QString::fromUtf8("space_6_5"));
        space_6_5->setGeometry(QRect(530, 310, 51, 31));
        space_6_5->setAlignment(Qt::AlignCenter);
        space_6_3 = new QLabel(gameFrame);
        space_6_3->setObjectName(QString::fromUtf8("space_6_3"));
        space_6_3->setGeometry(QRect(530, 170, 51, 31));
        space_6_3->setAlignment(Qt::AlignCenter);
        space_6_4 = new QLabel(gameFrame);
        space_6_4->setObjectName(QString::fromUtf8("space_6_4"));
        space_6_4->setGeometry(QRect(530, 240, 51, 31));
        space_6_4->setAlignment(Qt::AlignCenter);
        space_6_6 = new QLabel(gameFrame);
        space_6_6->setObjectName(QString::fromUtf8("space_6_6"));
        space_6_6->setGeometry(QRect(530, 380, 51, 31));
        space_6_6->setAlignment(Qt::AlignCenter);
        space_6_2 = new QLabel(gameFrame);
        space_6_2->setObjectName(QString::fromUtf8("space_6_2"));
        space_6_2->setGeometry(QRect(530, 100, 51, 31));
        space_6_2->setAlignment(Qt::AlignCenter);
        space_6_1 = new QLabel(gameFrame);
        space_6_1->setObjectName(QString::fromUtf8("space_6_1"));
        space_6_1->setGeometry(QRect(530, 30, 51, 31));
        space_6_1->setAlignment(Qt::AlignCenter);
        space_7_5 = new QLabel(gameFrame);
        space_7_5->setObjectName(QString::fromUtf8("space_7_5"));
        space_7_5->setGeometry(QRect(630, 310, 51, 31));
        space_7_5->setAlignment(Qt::AlignCenter);
        space_7_3 = new QLabel(gameFrame);
        space_7_3->setObjectName(QString::fromUtf8("space_7_3"));
        space_7_3->setGeometry(QRect(630, 170, 51, 31));
        space_7_3->setAlignment(Qt::AlignCenter);
        space_7_4 = new QLabel(gameFrame);
        space_7_4->setObjectName(QString::fromUtf8("space_7_4"));
        space_7_4->setGeometry(QRect(630, 240, 51, 31));
        space_7_4->setAlignment(Qt::AlignCenter);
        space_7_6 = new QLabel(gameFrame);
        space_7_6->setObjectName(QString::fromUtf8("space_7_6"));
        space_7_6->setGeometry(QRect(630, 380, 51, 31));
        space_7_6->setAlignment(Qt::AlignCenter);
        space_7_2 = new QLabel(gameFrame);
        space_7_2->setObjectName(QString::fromUtf8("space_7_2"));
        space_7_2->setGeometry(QRect(630, 100, 51, 31));
        space_7_2->setAlignment(Qt::AlignCenter);
        space_7_1 = new QLabel(gameFrame);
        space_7_1->setObjectName(QString::fromUtf8("space_7_1"));
        space_7_1->setGeometry(QRect(630, 30, 51, 31));
        space_7_1->setAlignment(Qt::AlignCenter);
        secondColButton = new QPushButton(gameSection);
        secondColButton->setObjectName(QString::fromUtf8("secondColButton"));
        secondColButton->setGeometry(QRect(240, 90, 91, 41));
        firstColButton = new QPushButton(gameSection);
        firstColButton->setObjectName(QString::fromUtf8("firstColButton"));
        firstColButton->setGeometry(QRect(140, 90, 91, 41));
        sixthButtonCol = new QPushButton(gameSection);
        sixthButtonCol->setObjectName(QString::fromUtf8("sixthButtonCol"));
        sixthButtonCol->setGeometry(QRect(640, 90, 91, 41));
        fourthColButton = new QPushButton(gameSection);
        fourthColButton->setObjectName(QString::fromUtf8("fourthColButton"));
        fourthColButton->setGeometry(QRect(440, 90, 91, 41));
        fifthColButton = new QPushButton(gameSection);
        fifthColButton->setObjectName(QString::fromUtf8("fifthColButton"));
        fifthColButton->setGeometry(QRect(540, 90, 91, 41));
        thirdColButton = new QPushButton(gameSection);
        thirdColButton->setObjectName(QString::fromUtf8("thirdColButton"));
        thirdColButton->setGeometry(QRect(340, 90, 91, 41));
        player_label = new QLabel(gameSection);
        player_label->setObjectName(QString::fromUtf8("player_label"));
        player_label->setGeometry(QRect(130, 50, 711, 31));
        player_label->setAlignment(Qt::AlignCenter);
        player_label->setWordWrap(false);
        instructionsButton = new QPushButton(gameSection);
        instructionsButton->setObjectName(QString::fromUtf8("instructionsButton"));
        instructionsButton->setGeometry(QRect(860, 0, 111, 41));
        seventhColButton = new QPushButton(gameSection);
        seventhColButton->setObjectName(QString::fromUtf8("seventhColButton"));
        seventhColButton->setGeometry(QRect(740, 90, 91, 41));
        pushButton = new QPushButton(gameSection);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(740, 0, 113, 41));
        pushButton_2 = new QPushButton(gameSection);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(740, 40, 113, 41));
        stackedWidget->addWidget(gameSection);
        connect4App->setCentralWidget(centralwidget);
        menubar = new QMenuBar(connect4App);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1004, 22));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        connect4App->setMenuBar(menubar);
        statusbar = new QStatusBar(connect4App);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        connect4App->setStatusBar(statusbar);

        menubar->addAction(menuFile->menuAction());
        menuFile->addAction(actionClose_Application_2);

        retranslateUi(connect4App);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(connect4App);
    } // setupUi

    void retranslateUi(QMainWindow *connect4App)
    {
        connect4App->setWindowTitle(QApplication::translate("connect4App", "connect4App", nullptr));
        actionClose_Application->setText(QApplication::translate("connect4App", "Close Application", nullptr));
        actionClose_Application_2->setText(QApplication::translate("connect4App", "Close Application", nullptr));
        nameLabel->setText(QApplication::translate("connect4App", "Player 1 Enter Your Name:", nullptr));
        redButton->setText(QApplication::translate("connect4App", "RED", nullptr));
        colorLabel->setText(QApplication::translate("connect4App", "Select Your Color:", nullptr));
        greenButton->setText(QApplication::translate("connect4App", "GREEN", nullptr));
        cyanButton->setText(QApplication::translate("connect4App", "CYAN", nullptr));
        blueButton->setText(QApplication::translate("connect4App", "BLUE", nullptr));
        yellowButton->setText(QApplication::translate("connect4App", "YELLOW", nullptr));
        magentaButton->setText(QApplication::translate("connect4App", "MAGENTA", nullptr));
        maroonButton->setText(QApplication::translate("connect4App", "MAROON", nullptr));
        goldButton->setText(QApplication::translate("connect4App", "GOLD", nullptr));
        darkMagButton->setText(QApplication::translate("connect4App", "DARK MAGENTA", nullptr));
        darkGreenButton->setText(QApplication::translate("connect4App", "DARK GREEN", nullptr));
        blackButton->setText(QApplication::translate("connect4App", "BLACK", nullptr));
        whiteButton->setText(QApplication::translate("connect4App", "WHITE", nullptr));
        nextButton->setText(QApplication::translate("connect4App", "NEXT", nullptr));
        currentColLabel_2->setText(QApplication::translate("connect4App", "Current Color:", nullptr));
        currentCol_2->setText(QString());
        nameLabel_2->setText(QApplication::translate("connect4App", "Player 2 Enter Your Name:", nullptr));
        redButton_2->setText(QApplication::translate("connect4App", "RED", nullptr));
        colorLabel_2->setText(QApplication::translate("connect4App", "Select Your Color:", nullptr));
        greenButton_2->setText(QApplication::translate("connect4App", "GREEN", nullptr));
        cyanButton_2->setText(QApplication::translate("connect4App", "CYAN", nullptr));
        blueButton_2->setText(QApplication::translate("connect4App", "BLUE", nullptr));
        yellowButton_2->setText(QApplication::translate("connect4App", "YELLOW", nullptr));
        magentaButton_2->setText(QApplication::translate("connect4App", "MAGENTA", nullptr));
        maroonButton_2->setText(QApplication::translate("connect4App", "MAROON", nullptr));
        goldButton_2->setText(QApplication::translate("connect4App", "GOLD", nullptr));
        darkMagButton_2->setText(QApplication::translate("connect4App", "DARK MAGENTA", nullptr));
        darkGreenButton_2->setText(QApplication::translate("connect4App", "DARK GREEN", nullptr));
        blackButton_2->setText(QApplication::translate("connect4App", "BLACK", nullptr));
        whiteButton_2->setText(QApplication::translate("connect4App", "WHITE", nullptr));
        nextButton_2->setText(QApplication::translate("connect4App", "NEXT", nullptr));
        currentColLabel->setText(QApplication::translate("connect4App", "Current Color:", nullptr));
        currentCol->setText(QString());
        nextButton_3->setText(QApplication::translate("connect4App", "NEXT", nullptr));
        label->setText(QApplication::translate("connect4App", "Who's Going First?", nullptr));
        name1Button->setText(QApplication::translate("connect4App", "PushButton", nullptr));
        name2Button->setText(QApplication::translate("connect4App", "PushButton", nullptr));
        space_1_1->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_1_2->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_1_3->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_1_5->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_1_4->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_1_6->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_2_5->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_2_3->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_2_4->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_2_6->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_2_2->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_2_1->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_3_5->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_3_3->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_3_4->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_3_6->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_3_2->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_3_1->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_4_5->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_4_3->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_4_4->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_4_6->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_4_2->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_4_1->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_5_5->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_5_3->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_5_4->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_5_6->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_5_2->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_5_1->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_6_5->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_6_3->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_6_4->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_6_6->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_6_2->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_6_1->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_7_5->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_7_3->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_7_4->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_7_6->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_7_2->setText(QApplication::translate("connect4App", "Space", nullptr));
        space_7_1->setText(QApplication::translate("connect4App", "Space", nullptr));
        secondColButton->setText(QApplication::translate("connect4App", "Drop Piece", nullptr));
        firstColButton->setText(QApplication::translate("connect4App", "Drop Piece", nullptr));
        sixthButtonCol->setText(QApplication::translate("connect4App", "Drop Piece", nullptr));
        fourthColButton->setText(QApplication::translate("connect4App", "Drop Piece", nullptr));
        fifthColButton->setText(QApplication::translate("connect4App", "Drop Piece", nullptr));
        thirdColButton->setText(QApplication::translate("connect4App", "Drop Piece", nullptr));
        player_label->setText(QApplication::translate("connect4App", "Player 1 turn", nullptr));
        instructionsButton->setText(QApplication::translate("connect4App", "Instructions", nullptr));
        seventhColButton->setText(QApplication::translate("connect4App", "Drop Piece", nullptr));
        pushButton->setText(QApplication::translate("connect4App", "Select Colors", nullptr));
        pushButton_2->setText(QApplication::translate("connect4App", "Themes", nullptr));
        menuFile->setTitle(QApplication::translate("connect4App", "File", nullptr));
    } // retranslateUi

};

namespace Ui {
    class connect4App: public Ui_connect4App {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CONNECT4APP_H
